### ISSUE TITLE
please i need a help for my problem in screen ,i am using PHONESPLOIT and i found this error

### ISSUE THREAD

**Issue by hossemtamsouh** [01010000-kumar/PhoneSploit#11]
[
![ScreenShot_20201022225431](https://user-images.githubusercontent.com/73261376/96930881-b485b200-14bc-11eb-8879-54a27fd36282.png)
](url)

**Comment by 01010000-kumar** [comment]
what linux distribution are you using?

**Comment by hossemtamsouh** [comment]
> what linux distribution are you using?

Iam using cygwin (windows 7 , 32bits)

**Comment by 01010000-kumar** [comment]
try doing to the adb directory and running the command `adb devices`

**Comment by hossemtamsouh** [comment]
> try doing to the adb directory and running the command `adb devices`

thanks 01010000-kumar
