### ISSUE TITLE
unable to connect to ip

### ISSUE THREAD

**Issue by Fluxx99** [01010000-kumar/PhoneSploit#2]
whenever i enter the android ip it always say unable to connect to (ip): Connection timed out

**Comment by 01010000-kumar** [comment]
did you enter the ip with a port?

**Comment by devesh-msns** [comment]
> did you enter the ip with a port?
> 
> somewhat like
> 192.168.0.12:5555
> 
> specifying the port won't work
> 
> the port is set to 5555 by default
> 
> let me know if you think default port is a bad idea

I didn't set it

**Comment by aerosol-can** [comment]
i don't see the problem


> > did you enter the ip with a port?
> > somewhat like
> > 192.168.0.12:5555
> > specifying the port won't work
> > the port is set to 5555 by default
> > let me know if you think default port is a bad idea
> 
> I didn't set it

i don't see the problem
