### ISSUE TITLE
Add support for termux.

### ISSUE THREAD

**Issue by whitedevil012** [01010000-kumar/PhoneSploit#5]
Even though termux support linux, I installed colorama and when I run phonesploit.py it still says adb is not found. I even extracted adb rar in phonesploit folder.

**Comment by 01010000-kumar** [comment]
https://github.com/01010000-kumar/PhoneSploit#if-adb-not-found

**Comment by whitedevil012** [comment]
This is the error I got after tried ur suggestion

boot                                              Reading package lists... Done
Building dependency tree                          Reading state information... Done
E: Unable to locate package android-tools-adb
E: Unable to locate package android-tools-fastboot

**Comment by 01010000-kumar** [comment]
adb packages are not available for termux


maybe this would help: https://github.com/MasterDevX/Termux-ADB
